### ISSUE TITLE
The URL couldn't be validated. Response does not match challenge

### ISSUE THREAD

**Issue by ashwinijul13** [somaraj/Facebook-ASP.NET-Webhook#10]
Thank you for API code

While doing setup in facebook getting error

**The URL couldn't be validated. Response does not match challenge, expected value="1752482085", received="{\"version\":{\"major\":..."**

can you please suggest what should i do?

**Comment by somaraj** [comment]
do you have a valid SSL ?

**Comment by ashwinijul13** [comment]
Thank you for your reply
Yes SSL is there
 
That issue was resolved by changing framework from .net core to .net 4.5
 
But when i am testing application in facebook giving below error:

Can you please suggest

|Post Method called Response status code does not indicate success: 400 (Bad Request).
2021-09-15 15:35:39.4052|INFO|WebApplication1.Controllers.FBWebhooksController|Post Method called    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebApplication1.Controllers.FBWebhooksController.<Post>d__2.MoveNext()

**Comment by ebrahim3108** [comment]
Hi Somaraj,

Thank you for sharing your code. It really helped. Unfortunately I am facing the same problem as Ashwin. 
Getting the below error 

System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).     
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     
at I.Controllers.WebhooksController.<Post>d__2.MoveNext()

can you please help us resolve this. 
thank you

**Comment by MohammedMubeen** [comment]
Hi @ebrahim3108 , @ashwinijul13 , How you got the solution? 400 bad request.

var response = await httpClientLead.GetStringAsync(formUrl);
